// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Buy is the golang structure of table buy for DAO operations like Where/Data.
type Buy struct {
	g.Meta     `orm:"table:buy, do:true"`
	Id         interface{} // pk
	Uid        interface{} // User ID
	Pid        interface{} // Prompt ID
	CreateTime *gtime.Time // Created Time
	UpdateTime *gtime.Time // Updated Time
}
