// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Comment is the golang structure of table comment for DAO operations like Where/Data.
type Comment struct {
	g.Meta     `orm:"table:comment, do:true"`
	Id         interface{} // pk
	Cid        interface{} // Comment ID
	Uid        interface{} // User ID
	Pid        interface{} // Prompt ID
	Text       interface{} // Comment content
	ParentCid  interface{} // Reply Comment ID
	CreateTime *gtime.Time // Created Time
	UpdateTime *gtime.Time // Updated Time
}
