// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Prompt is the golang structure of table prompt for DAO operations like Where/Data.
type Prompt struct {
	g.Meta     `orm:"table:prompt, do:true"`
	Id         interface{} // pk
	Pid        interface{} // Prompt ID
	Name       interface{} // Prompt Name
	Desc       interface{} // Description
	Price      interface{} // Prompt Price
	Type       interface{} // Prompt Type
	Content    interface{} // Prompt Content
	Params     interface{} // Prompt Params
	Author     interface{} // Prompt Author
	Taglist    interface{} // Prompt Tag
	Avatar     interface{} // Prompt 图片
	Examples   interface{} // Prompt examples
	CreateTime *gtime.Time // Created Time
	UpdateTime *gtime.Time // Updated Time
}
