// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta     `orm:"table:user, do:true"`
	Id         interface{} // pk
	Uid        interface{} // User ID
	Username   interface{} // User Name
	Score      interface{} //
	Address    interface{} // Wallet Address
	Avatar     interface{} // 头像
	Desc       interface{} // Description
	CreateTime *gtime.Time // Created Time
	UpdateTime *gtime.Time // Updated Time
}
