// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Prompt is the golang structure for table prompt.
type Prompt struct {
	Id         uint        `json:"id"         description:"pk"`
	Pid        string      `json:"pid"        description:"Prompt ID"`
	Name       string      `json:"name"       description:"Prompt Name"`
	Desc       string      `json:"desc"       description:"Description"`
	Price      float64     `json:"price"      description:"Prompt Price"`
	Type       uint        `json:"type"       description:"Prompt Type"`
	Content    string      `json:"content"    description:"Prompt Content"`
	Params     string      `json:"params"     description:"Prompt Params"`
	Author     string      `json:"author"     description:"Prompt Author"`
	Taglist    string      `json:"taglist"    description:"Prompt Tag"`
	Avatar     string      `json:"avatar"     description:"Prompt 图片"`
	Examples   string      `json:"examples"   description:"Prompt examples"`
	CreateTime *gtime.Time `json:"createTime" description:"Created Time"`
	UpdateTime *gtime.Time `json:"updateTime" description:"Updated Time"`
}
