// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	v1 "github.com/gogf/gf-demo-user/v2/api/v1"
)

type (
	IChatgpt interface {
		Ask(ctx context.Context, in *v1.AskReq) (*v1.AskRes, error)
	}
)

var (
	localChatgpt IChatgpt
)

func Chatgpt() IChatgpt {
	if localChatgpt == nil {
		panic("implement not found for interface IChatgpt, forgot register?")
	}
	return localChatgpt
}

func RegisterChatgpt(i IChatgpt) {
	localChatgpt = i
}
