// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	v1 "github.com/gogf/gf-demo-user/v2/api/v1"
)

type (
	IUser interface {
		ChangeProfile(ctx context.Context, in *v1.UserChangeProfileReq) (err error)
		Login(ctx context.Context, in *v1.UserLoginReq) (*v1.UserLoginRes, error)
		IsSignedIn(ctx context.Context) bool
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
