[package]
name = "redot-core-primitives"
description = ""
version = "0.1.0"
authors = ["DKLee <xiuerdwy@gmail.com>"]
edition = "2021"
repository = "https://github.com/ZeroDAO/redot"
keywords = ["substrate", "pallet", "macro", "configuration"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow = { version = "1.0.66", optional = true }
rand = { version = "0.8.4", optional = true }
serde = { version = "1.0.163", optional = true }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"], default-features = false }
frost-ed25519 = { version="1.0.0-rc.0", default-features = false, optional = true }
scale-info = { version = "2.2.0", default-features = false, features = ["derive"] }
ed25519-consensus = { version = "2.1.0", default-features = false }

# Substrate
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
cumulus-primitives-core = { default-features = false, git = "https://github.com/paritytech/cumulus.git", branch = "polkadot-v1.0.0" }

# [dev-dependencies]
# serde = { version = "1.0.163" }

[features]
default = ["std"]
std = [
	"rand",
	"anyhow",
	"codec/std",
	"scale-info/std",
	"serde/std",
	"sp-api/std",
	# "frost-ed25519/serialization",
	"frost-ed25519",
	"cumulus-primitives-core/std",
]
