/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    colors: {
      coreColors: {
        primary: "#003E1F",
        secondary: "#73BA9B",
        tertiary: "#D5F2E3",
        error: "#D90429",
        neutral: "#8AA6A3",
        neutralVariant: "#BFBFBF",
      },
      schemes: {
        light: {
          primary: "#006D3B",
          onPrimary: "#FFFFFF",
          primaryContainer: "#99F7B5",
          onPrimaryContainer: "#00210E",
          primaryFixed: "#99F7B5",
          onPrimaryFixed: "#00210E",
          primaryFixedDim: "#7DDA9B",
          onPrimaryFixedVariant: "#00522B",
          secondary: "#006C4E",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#87F8C9",
          onSecondaryContainer: "#002115",
          secondaryFixed: "#87F8C9",
          onSecondaryFixed: "#002115",
          secondaryFixedDim: "#69DBAE",
          onSecondaryFixedVariant: "#00513A",
          tertiary: "#006C50",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#84F8CC",
          onTertiaryContainer: "#002116",
          tertiaryFixed: "#84F8CC",
          onTertiaryFixed: "#002116",
          tertiaryFixedDim: "#67DBB1",
          onTertiaryFixedVariant: "#00513C",
          error: "#BF0022",
          onError: "#FFFFFF",
          errorContainer: "#FFDAD7",
          onErrorContainer: "#410005",
          outline: "#6F797A",
          background: "#FAFDFB",
          onBackground: "#191C1C",
          surface: "#F7FAF8",
          onSurface: "#191C1C",
          surfaceVariant: "#DBE4E6",
          onSurfaceVariant: "#3F484A",
          inverseSurface: "#2D3130",
          inverseOnSurface: "#EFF1F0",
          inversePrimary: "#7DDA9B",
          shadow: "#000000",
          surfaceTint: "#006D3B",
          outlineVariant: "#BFC8CA",
          scrim: "#000000",
          surfaceContainerHighest: "#E0E3E2",
          surfaceContainerHigh: "#E6E9E7",
          surfaceContainer: "#ECEEED",
          surfaceContainerLow: "#F2F4F3",
          surfaceContainerLowest: "#FFFFFF",
          surfaceBright: "#F7FAF8",
          surfaceDim: "#D8DBD9",
        },
        dark: {
          primary: "#7DDA9B",
          onPrimary: "#00391C",
          primaryContainer: "#00522B",
          onPrimaryContainer: "#99F7B5",
          primaryFixed: "#99F7B5",
          onPrimaryFixed: "#00210E",
          primaryFixedDim: "#7DDA9B",
          onPrimaryFixedVariant: "#00522B",
          secondary: "#69DBAE",
          onSecondary: "#003827",
          secondaryContainer: "#00513A",
          onSecondaryContainer: "#87F8C9",
          secondaryFixed: "#87F8C9",
          onSecondaryFixed: "#002115",
          secondaryFixedDim: "#69DBAE",
          onSecondaryFixedVariant: "#00513A",
          tertiary: "#67DBB1",
          onTertiary: "#003828",
          tertiaryContainer: "#00513C",
          onTertiaryContainer: "#84F8CC",
          tertiaryFixed: "#84F8CC",
          onTertiaryFixed: "#002116",
          tertiaryFixedDim: "#67DBB1",
          onTertiaryFixedVariant: "#00513C",
          error: "#FFB3AF",
          onError: "#68000E",
          errorContainer: "#930018",
          onErrorContainer: "#FFDAD7",
          outline: "#899294",
          background: "#191C1C",
          onBackground: "#E0E3E2",
          surface: "#101414",
          onSurface: "#C4C7C6",
          surfaceVariant: "#3F484A",
          onSurfaceVariant: "#BFC8CA",
          inverseSurface: "#E0E3E2",
          inverseOnSurface: "#191C1C",
          inversePrimary: "#006D3B",
          shadow: "#000000",
          surfaceTint: "#7DDA9B",
          outlineVariant: "#3F484A",
          scrim: "#000000",
          surfaceContainerHighest: "#323535",
          surfaceContainerHigh: "#272B2A",
          surfaceContainer: "#1D2020",
          surfaceContainerLow: "#191C1C",
          surfaceContainerLowest: "#0B0F0E",
          surfaceBright: "#363A39",
          surfaceDim: "#101414",
        },
      },
    },
    extend: {},
  },
  plugins: [],
};
