// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Comment is the golang structure for table comment.
type Comment struct {
	Id         uint        `json:"id"         description:"pk"`
	Cid        string      `json:"cid"        description:"Comment ID"`
	Uid        string      `json:"uid"        description:"User ID"`
	Pid        string      `json:"pid"        description:"Prompt ID"`
	Text       string      `json:"text"       description:"Comment content"`
	ParentCid  string      `json:"parentCid"  description:"Reply Comment ID"`
	CreateTime *gtime.Time `json:"createTime" description:"Created Time"`
	UpdateTime *gtime.Time `json:"updateTime" description:"Updated Time"`
}
