// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Promptlike is the golang structure for table promptlike.
type Promptlike struct {
	Id         uint        `json:"id"         description:"pk"`
	Uid        string      `json:"uid"        description:"User ID"`
	Pid        string      `json:"pid"        description:"Prompt ID"`
	Like       int         `json:"like"       description:"User like(1) or dislike(-1) prompt"`
	CreateTime *gtime.Time `json:"createTime" description:"Created Time"`
	UpdateTime *gtime.Time `json:"updateTime" description:"Updated Time"`
}
