// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id         uint        `json:"id"         description:"pk"`
	Uid        string      `json:"uid"        description:"User ID"`
	Username   string      `json:"username"   description:"User Name"`
	Score      float64     `json:"score"      description:""`
	Address    string      `json:"address"    description:"Wallet Address"`
	Avatar     string      `json:"avatar"     description:"头像"`
	Desc       string      `json:"desc"       description:"Description"`
	CreateTime *gtime.Time `json:"createTime" description:"Created Time"`
	UpdateTime *gtime.Time `json:"updateTime" description:"Updated Time"`
}
