/**
 * A limited list of rpc methods that are supported by an RPC provider. Used for testing.
 * Such a list is supposed to be generated by a custom configuration with `typegen`.
 */
export const LimitedRpcList = {
  chain: [
    'getBlock',
    'getBlockHash',
    'getFinalizedHead',
    'getHeader',
    'subscribeAllHeads',
    'subscribeFinalizedHeads',
    'subscribeNewHeads',
  ],
  system: [
    'accountNextIndex',
    'addLogFilter',
    'addReservedPeer',
    'chain',
    'chainType',
    'dryRun',
    'health',
    'localListenAddresses',
    'localPeerId',
    'name',
    'networkState',
    'nodeRoles',
    'peers',
    'properties',
    'removeReservedPeer',
    'reservedPeers',
    'resetLogFilter',
    'syncState',
    'version',
  ],
} as const;
