// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/dao/internal"
)

// internalBuyDao is internal type for wrapping internal DAO implements.
type internalBuyDao = *internal.BuyDao

// buyDao is the data access object for table buy.
// You can define custom methods on it to extend its functionality as you wish.
type buyDao struct {
	internalBuyDao
}

var (
	// Buy is globally public accessible object for table buy operations.
	Buy = buyDao{
		internal.NewBuyDao(),
	}
)

// Fill with you ideas below.
