// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/dao/internal"
)

// internalCommentDao is internal type for wrapping internal DAO implements.
type internalCommentDao = *internal.CommentDao

// commentDao is the data access object for table comment.
// You can define custom methods on it to extend its functionality as you wish.
type commentDao struct {
	internalCommentDao
}

var (
	// Comment is globally public accessible object for table comment operations.
	Comment = commentDao{
		internal.NewCommentDao(),
	}
)

// Fill with you ideas below.
