// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/dao/internal"
)

// internalPromptlikeDao is internal type for wrapping internal DAO implements.
type internalPromptlikeDao = *internal.PromptlikeDao

// promptlikeDao is the data access object for table promptlike.
// You can define custom methods on it to extend its functionality as you wish.
type promptlikeDao struct {
	internalPromptlikeDao
}

var (
	// Promptlike is globally public accessible object for table promptlike operations.
	Promptlike = promptlikeDao{
		internal.NewPromptlikeDao(),
	}
)

// Fill with you ideas below.
